env:
  browser: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:prettier/recommended

parserOptions:
  ecmaVersion: 12
  sourceType: module

rules:
  no-unused-vars: warn
  no-console: off
  indent: 
    - error
    - 2
  quotes:
    - error
    - single
